### ISSUE TITLE
Init.sh did not work

### ISSUE THREAD

**Issue by jamesecorrenti** [kmcgaffey/dockserv#1]
chmod: cannot access '/opt/admin.git/.git/hooks/post-receive': No such file or directory

**Comment by kmcgaffey** [comment]
Hmm lemme take a look.

**Comment by kmcgaffey** [comment]
Ok I fixed that issue. The file was being added to the wrong directory in the Dockerfile. Though it looks like there's an issue with signing into the git server with ssh as well, leading me to believe a forgot to make acommit before I pushed. I will check my dev system when I get in tomorrow.
